version: "3.9"

services:
  web-app-nginx:
    image: nginx:1.19-alpine
    ports:
      - "81:80"
      - "443:443"
    volumes:
      - ./.docker/front-end/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./front-end/dist:/usr/share/nginx/html
